wishDream:
  database:
    database: wishDream
    host: localhost
    password: wishDream
    port: 5430
    user: wishDream
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5430/wishDream    username: wishDream
    password: wishDream
    