logging:
  level:
    org:
      hibernate: DEBUG
      springframework:
        security: DEBUG
        data:
          mongodb: DEBUG
          r2dbc: DEBUG
        web: DEBUG
    root: INFO
    tomcat: INFO
server:
  error:
    include-exception: true
    include-stacktrace: never
  port: 8030
kafka:
  server: localhost:9092
  topics: alarm-topic
spring:
  jackson:
    default-property-inclusion: NON_NULL
  data:
    mongodb:
      host: localhost
      port: 27017
      database: wishDream
  main:
    allow-bean-definition-overriding: true
  webflux:
    static-path-pattern: "/static/**"
  resources:
    static-locations:
    - "classpath:/static/"
  application:
    name: WishDream
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 38b0b3993dcff7e6614324b5274d25cb
            client-secret: F1yaolgLjCLEP7VCwzgaxrnFUWGtQEdA 
wishDream:
  database:
    url: jdbc:postgresql://localhost:5430/wishDream
    user: wishdream
    password: wishdream
    database: wishDream
    host: localhost
    port: 5430