logging:
  level:
    org:
      hibernate: DEBUG
      springframework:
        data:
          r2dbc: DEBUG
        web: DEBUG
    root: INFO
    tomcat: INFO
server:
  error:
    include-exception: true
    include-stacktrace: never
  port: 8080
spring:
  jackson:
    default-property-inclusion: NON_NULL
  data:
    mongodb:
      host: localhost
      port: 27017
      database: wishDream
  main:
    allow-bean-definition-overriding: true
  webflux:
    static-path-pattern: "/static/**"
  resources:
    static-locations:
    - "classpath:/static/"
  application:
    name: WishDream
wishDream:
  database:
    url: jdbc:postgresql://localhost:5430/wishDream
    user: wishdream
    password: wishdream
    database: wishDream
    host: localhost
    port: 5430