logging:
  level:
    org:
      hibernate: DEBUG
      springframework:
        data:
          r2dbc: DEBUG
        web: DEBUG
    root: WARN
    tomcat: INFO
server:
  error:
    include-exception: true
    include-stacktrace: never
  port: 8080
spring:
  application:
    name: WishDream
  thymeleaf:
    cache: 'false'
    check-template-location: true
    encoding: UTF-8
    prefix: classpath:/static/
    suffix: .html
    template-resolver-order: 0
wishDream:
  database:
    url: jdbc:postgresql://localhost:5430/wishDream
    user: wishdream
    password: wishdream
    database: wishDream
    host: localhost
    port: 5430